routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'SerfLinksLoggerController@index')->name('welcome');
/* Return public data for AngularJS uses at `welcome` */
Route::get('/api/clicks', 'ClicksResourceController@apiFullList')->name('api.home-page-data');
/* Page of click processing */
Route::get('/click', 'SerfLinksLoggerController@trackingLinkAnalyzer')->name('serf-link-logger.analyzer');
Route::get('/success/{id}', 'SerfLinksLoggerController@trackingResult')->name('serf-link-logger.r-success');
Route::get('/error/{id}', 'SerfLinksLoggerController@trackingResult')->name('serf-link-logger.r-fail');
Route::get('/link-generator', 'SerfLinksLoggerController@exampleLinksDemo')->name('serf-link-logger.links-generator');

/* Fully resource map for Domains */
Route::resource('bad-domains', 'BadDomainsResourceController');

app/Models/BadDomain.php
<?php

namespace Tapgerine\TSp\Models;

/**
 * Class BadDomain
 * @package Tapgerine\TSp\Models
 * @extends Tapgerine\TSp\Models\NonTimeStampsModel
 *
 * @property int $id
 * @property string $name
 */
class BadDomain extends NonTimeStampsModel
{
    /* override default value */
    protected $perPage = 30;
    protected $fillable = ['name'];
    
    protected static $editingMethods = [
        'PUT', 'PATCH'
    ];
    
    /**
     * @param string $method
     * @return array
     */
    public function rules(string $method = 'POST')
    {
        $patchConditionString = in_array($method, self::$editingMethods) ? (',' . $this->id) : '';
        
        return [
            'name' => 'required|url|unique:bad_domains,name' . $patchConditionString
        ];
    }
    
    /**
     * @return mixed
     */
    public function getPaginatedList()
    {
        return self::paginate();
    }
    
    /**
     * @param string $link
     * @return bool
     */
    public static function checkIsDomainBad(string $link)
    {
        if (!$link) {
            return false;
        }
        
        $link = self::constructCleanUrlHelper($link);
        
        /* set like valid users without referral link */
        if (!$link) {
            return false;
        }
        
        return boolval(self::where('name', 'like', '%' . $link . '%')->count());
    }
    
    protected static function constructCleanUrlHelper(string $link)
    {
        $objLink = parse_url($link);
        return (isset($objLink['host'])) ? $objLink['host'] : '';
    }
}

resources/views/bad-domains/_form.blade.php
<div class="form-group">
    {!! Form::label('Type the full link...') !!}
    {!! Form::text('name', $dataProvider->name, [
        'class'=>'form-control',
        'placeholder' => 'http://example.com',
        'autofocus' => 1
    ]) !!}
</div>
<div class="form-group">
    {!! Form::submit('Save', ['class'=>'btn btn-primary']) !!}
</div>

<a class="btn btn-default" href="{{route('bad-domains.index')}}">Go back</a>

resources/views/bad-domains/create.blade.php
<?php
/**
 * Project:     tapgerine
 * File:        list.blade.php
 * Author:      planet17
 * DateTime:    M05.D25.2017 11:38 PM
 */
?>
@extends('layouts.default')
@section('body')

    <h1>Create</h1>

    <div class="errors">
        {{ Html::ul($errors->all()) }}
    </div>

    {!! Form::open(['route'=> 'bad-domains.store']) !!}
        @include('bad-domains._form')
    {!! Form::close() !!}
@stop

resources/views/bad-domains/edit.blade.php
<?php
/**
 * Project:     tapgerine
 * File:        list.blade.php
 * Author:      planet17
 * DateTime:    M05.D25.2017 11:38 PM
 */
?>
@extends('layouts.default')
@section('body')

    <h1>Edit</h1>

    <div class="errors">
        {{ Html::ul($errors->all()) }}
    </div>

    {!! Form::open([
        'route'=> ['bad-domains.update', $dataProvider->id],
        'method' => 'put'
    ]) !!}
        @include('bad-domains._form')
    {!! Form::close() !!}

    {!! Form::open([
        'route' => ['bad-domains.destroy', $dataProvider->id],
        'method' => 'delete'
    ]) !!}
    {!! Form::submit('Remove', ['class' => 'btn btn-danger glyphicon glyphicon-trash']) !!}
    {!! Form::close() !!}
@stop

resources/views/bad-domains/list.blade.php
<?php
/**
 * Project:     tapgerine
 * File:        list.blade.php
 * Author:      planet17
 * DateTime:    M05.D25.2017 11:38 PM
 */
?>
@extends('layouts.default')
@section('body')
    <div class="flex-center position-ref cut-height">
        @include('common._cn-links')
    </div>

    @if(count($data))
        <div class="flex-center position-ref">
            <h2>List (total {{$data->total()}} BadDomains)</h2>
            <h3>Page {{$data->currentPage()}} from {{$data->lastPage()}}</h3>
        </div>

        @if(Session::has('message'))
            <div class="alert alert-info">
                {!! Session::get('message') !!}
            </div>
        @endif

        <div class="f-right">
            <a class="btn btn-success" href="{{route('bad-domains.create')}}">Create</a>
        </div>

        <div class="f-center position-ref data">
            <ul class="flex-list">
                @foreach($data as $domain)
                    <li>
                        <div class="id">
                            {{$domain->id}}
                        </div>

                        <div class="name">
                            {{$domain->name}}
                        </div>

                        <div class="edit">
                            {!! link_to_route(
                                'bad-domains.edit',
                                'Edit',
                                $domain->id,
                                ['class' =>  'btn btn-small btn-warning']
                            ) !!}
                        </div>
                    </li>
                @endforeach
            </ul>
        </div>
        <div class="flex f-center position-ref pagination">
            {{$data->links()}}
        </div>
    @else
        <div class="flex-center position-ref">
            <h2>Bad Domains does not found.</h2>
        </div>
    @endif
@stop